### ISSUE TITLE
Ubuntu can't successfully deploy Chinese documents

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/docs-cn#19]
@0xTim 
Hi Tim
After several recent PRs were merged, it was not updated to the website: https://cn.docs.vapor.codes/4.0/deploy/heroku/
I'm not quite sure which step is the issue.

Can you help to check this ```./github-actions/deploy-docs-cn.sh``` [script](https://github.com/vapor/docs-cn/blob/main/.github/workflows/deploy.yml) on Ubuntu server?

![image](https://user-images.githubusercontent.com/16829428/159113451-cc963e90-bd93-4e0b-9789-899a95474539.png)

![image](https://user-images.githubusercontent.com/16829428/159113482-b4e250a9-df2f-4af5-9bb6-3c9fbd2fc6af.png)

**Comment by 0xTim** [comment]
@Jinxiansen OK we're planning to change the deployment of the docs anyway so since this is causing issues I'll just bring that forward

**Comment by Jinxiansen** [comment]
Well, look forward to new ways.

**Comment by Jinxiansen** [comment]
![image](https://user-images.githubusercontent.com/16829428/159662473-da1ccac3-e24a-443f-96aa-dc71ccf7176d.png)

@BennyDeBock 
Hi, Benny
The script seems to have failed to execute, can you confirm it?

**Comment by BennyDeBock** [comment]
@Jinxiansen I can confirm indeed that the script has failed. I'll continue working on it today. For some reason it doesn't work (even if it's mainly the same script as the german documentation).

**Comment by BennyDeBock** [comment]
@Jinxiansen It's supposed to be online.
The invalidation step failed because the `DISTRIBUTION_ID` hasn't been updated yet on the repo (something I unfortunately cannot do) so I did it manually

However @0xTim still needs to do the DNS stuff from what I know and then the site should be fully running from AWS

**Comment by 0xTim** [comment]
This is all updated. Might take a bit for DNS changes to propagate and caches to refresh but working for me
